# Site settings
title:       Marc Climent
email:       climens@climens.net
author:      Marc Climent
description: "Blog about my experiences as a developer, geek and father."
baseurl:     ""
url:         "http://codelog.climens.net"

# Sitemap
gems:
  - jekyll-sitemap

# Google analytics
google_analytics: UA-310639-6

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: mcliment
twitter_username: climens
google_plus_id: +MarcCliment
linkedin_username: mcliment
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
highlighter: rouge
markdown:     kramdown
#permalink:    pretty
permalink:    /:year/:month/:day/:title/
paginate:     5
sass:
  compressed: true
